### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by christian-blades-cb** [janestreet/iron#4]
I'd love to have some build instructions for Iron. 

I want to try Iron and see if it's something my team could benefit from, but I'm not an Ocaml guy and trying to build this is baffling me.

**Comment by dwang20151005** [comment]
Unfortunately, the answer is that we know you won't be able to set up an external instance, and it'll take nontrivial work to make that possible.  I'll propose internally that we delete this repo, because at the moment it's just a trap.

I think our current approach to getting the iron workflow out there is to blog about it and hope that someone will incorporate the workflow into a github client: 

https://blog.janestreet.com/putting-the-i-back-in-ide-towards-a-github-explorer/

https://blog.janestreet.com/code-review-that-isnt-boring/
https://blog.janestreet.com/scrutinizing-your-code-in-style/
https://blog.janestreet.com/ironing-out-your-release-process/

https://blog.janestreet.com/patch-review-vs-diff-review-revisited/

https://blog.janestreet.com/designing-a-code-review-tool-part-1/
https://blog.janestreet.com/designing-a-code-review-tool-part-2-patches-or-diffs/
